<?xml version="1.0"?>
<package format="3">
  <name>robot_hmi_backend</name>
  <version>0.0.0</version>
  <description>Robot5/Robot11 공통 탑재 HMI 백엔드</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>
  <depend>rclpy</depend>
  <depend>robot_status</depend>
  <exec_depend>python3-fastapi</exec_depend>
  <exec_depend>python3-uvicorn</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
